FROM golang

WORKDIR ${GOPATH}/src/github.com/allezsans/yamato/go

COPY go ./

RUN go get -u github.com/golang/dep/cmd/dep \
    && dep ensure --vendor-only \
    && go install \
    && rm -rf ${GOPATH}/src/github.com


CMD ["${GOPATH}/bin/go"]
