version: '2'
services:
  yamato:
    build: .
    container_name: yamato
    volumes:
    - "../go:/go/src/github.com/allezsans/yamato/go"
    command: go run main.go
    env_file:
    - .env.container
