steps:
  - name: 'gcr.io/cloud-builders/go'
    args: [ 'get', '-u', 'github.com/golang/dep/cmd/dep' ]
    env: ['GOPATH=/tmp']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'Dockerfile.production', '-t', 'gcr.io/$PROJECT_ID/yamato:${_COMMIT_ID}', '.' ]
images:
- 'gcr.io/$PROJECT_ID/yamato'
