version: '2'
services:
  yamato:
    build:
      context:  ..
      dockerfile: Dockerfile.development
    volumes:
    - "../go:/go/src/github.com/allezsans/yamato/go"
    command: go run main.go
    env_file:
    - .env.container
